### PR TITLE
octicon url change

### PR DESCRIPTION
**Pull request by noraj**
cf. https://github.com/primer/octicons

### CODE REVIEW

**Review by geoffreymcgill — APPROVED** [review]
Thanks for fixing the link!

**Comment by noraj** [comment]
Despite the PR been merged, the change seems not live yet.

**Comment by geoffreymcgill** [comment]
The change is live for me and appears to be correct. 

https://retype.com/configuration/project/#icon

**Comment by noraj** [comment]
It must have been a hard to kill cache. Sometimes `CTRL+F5` doesn't really force cache refresh.

**Pull request merged**
